unit FrmDM_Cadastro;

interface

uses
  SysUtils, Classes, DB, ZAbstractDataset,
  ZDataset, ZAbstractRODataset, ZSqlMonitor, ZSqlUpdate;

type
  TDM_CADASTRO = class(TDataModule)
    Z_Usuario: TZQuery;
    Z_Tabela: TZQuery;
    Z_Permissao: TZQuery;
    DS_Usuario: TDataSource;
    DS_Tabela: TDataSource;
    DS_Permissao: TDataSource;
    Z_Curinga_02: TZQuery;
    Z_Curinga_01: TZQuery;
    DS_Curinga_01: TDataSource;
    DS_Curinga_02: TDataSource;
    UP_Permissao: TZUpdateSQL;
    Z_Empresa: TZQuery;
    DS_Empresa: TDataSource;
    Z_Estado: TZQuery;
    Z_Cidade: TZQuery;
    Z_Bairro: TZQuery;
    Z_Logradouro: TZQuery;
    DS_Estado: TDataSource;
    DS_Cidade: TDataSource;
    DS_Bairro: TDataSource;
    DS_Logradouro: TDataSource;
    UP_Logradouro: TZUpdateSQL;
    Z_TabelaID_TABELA: TIntegerField;
    Z_TabelaNOME: TStringField;
    Z_TabelaOBS: TStringField;
    Z_PermissaoID_USUARIO: TIntegerField;
    Z_PermissaoID_TABELA: TIntegerField;
    Z_PermissaoXSELECT: TStringField;
    Z_PermissaoXDELETE: TStringField;
    Z_PermissaoXINSERT: TStringField;
    Z_PermissaoXUPDATE: TStringField;
    Z_PermissaoNOME: TStringField;
    Z_PermissaoNOME_1: TStringField;
    Z_EmpresaID_EMPRESA: TIntegerField;
    Z_EmpresaFAIXA_INICIAL: TIntegerField;
    Z_EmpresaFAIXA_FINAL: TIntegerField;
    Z_EmpresaIPLOCAL: TStringField;
    Z_EmpresaIPWWW: TStringField;
    Z_EmpresaNOME: TStringField;
    Z_EmpresaNOME_FANTASIA: TStringField;
    Z_EmpresaCNPJ: TStringField;
    Z_EmpresaIE: TStringField;
    Z_EmpresaIM: TStringField;
    Z_EmpresaEMAIL: TStringField;
    Z_EmpresaNASCIMENTO: TDateField;
    Z_EmpresaOBS: TStringField;
    Z_EmpresaTELEFONE1: TStringField;
    Z_EmpresaTELEFONE2: TStringField;
    Z_EmpresaCELULAR: TStringField;
    Z_EmpresaFAX: TStringField;
    Z_EmpresaRUA: TStringField;
    Z_EmpresaNUMERO: TIntegerField;
    Z_EmpresaCIDADE: TStringField;
    Z_EmpresaBAIRRO: TStringField;
    Z_EmpresaCEP: TStringField;
    Z_EmpresaMENSAGEM: TMemoField;
    Z_EmpresaLOGO: TStringField;
    Z_EmpresaFUNDO: TStringField;
    Z_EmpresaDATA: TDateField;
    Z_EmpresaATIVO: TStringField;
    Z_EstadoID_SIGLA: TIntegerField;
    Z_EstadoNOME: TStringField;
    Z_CidadeID_CIDADE: TIntegerField;
    Z_CidadeNOME: TStringField;
    Z_BairroID_BAIRRO: TIntegerField;
    Z_BairroNOME: TStringField;
    Z_EstadoSIGLA: TStringField;
    Z_CidadeCEP_INICIAL: TStringField;
    Z_CidadeCEP_FINAL: TStringField;
    Z_Endereco_Tipo: TZQuery;
    DS_Endereco_Tipo: TDataSource;
    Z_Pessoa_Tipo: TZQuery;
    DS_Pessoa_Tipo: TDataSource;
    Z_Ocupacao: TZQuery;
    Z_OcupacaoID_OCUPACAO: TIntegerField;
    Z_OcupacaoCBO: TStringField;
    Z_OcupacaoNOME: TStringField;
    Z_OcupacaoOBS: TStringField;
    DS_Ocupacao: TDataSource;
    Z_Pessoa: TZQuery;
    Z_Endereco: TZQuery;
    Z_Telefone: TZQuery;
    DS_Pessoa: TDataSource;
    DS_Endereco: TDataSource;
    DS_Telefone: TDataSource;
    UP_Pessoa: TZUpdateSQL;
    UP_Telefone: TZUpdateSQL;
    UP_Endereco: TZUpdateSQL;
    Z_EnderecoID_PESSOA: TIntegerField;
    Z_EnderecoID_LOGRADOURO: TIntegerField;
    Z_EnderecoID_ENDERECO_TIPO: TIntegerField;
    Z_EnderecoNUMERO: TSmallintField;
    Z_EnderecoCOMPLEMENTO: TStringField;
    Z_EnderecoMALADIRETA: TStringField;
    Z_EnderecoOBS: TStringField;
    Z_EnderecoENDTIPO: TStringField;
    Z_EnderecoCEP: TStringField;
    Z_EnderecoTIPORUA: TStringField;
    Z_EnderecoRUA: TStringField;
    Z_EnderecoBAIRRO: TStringField;
    Z_EnderecoCIDADE: TStringField;
    Z_EnderecoESTADO: TStringField;
    Z_TelefoneID_PESSOA: TIntegerField;
    Z_TelefoneID_ENDERECO_TIPO: TIntegerField;
    Z_TelefoneDDD: TStringField;
    Z_TelefoneRAMAL: TStringField;
    Z_TelefoneNUMERO: TStringField;
    Z_TelefoneCONTATO: TStringField;
    Z_TelefoneMALADIRETA: TStringField;
    Z_TelefoneTIPO: TStringField;
    Z_TelefoneID_TELEFONE: TIntegerField;
    Z_Interesse: TZQuery;
    UP_Interesse: TZUpdateSQL;
    DS_Interesse: TDataSource;
    Z_InteresseID_PESSOA: TIntegerField;
    Z_InteresseID_LOGRADOURO: TIntegerField;
    Z_InteresseOBS: TStringField;
    Z_InteresseATIVO: TStringField;
    Z_InteresseCEP: TStringField;
    Z_InteresseTIPORUA: TStringField;
    Z_InteresseRUA: TStringField;
    Z_InteresseBAIRRO: TStringField;
    Z_InteresseCIDADE: TStringField;
    Z_InteresseESTADO: TStringField;
    Z_InteresseID_PESSOA_INTERESSE: TIntegerField;
    Z_Imovel_Tipo: TZQuery;
    DS_Imovel_Tipo: TDataSource;
    Z_Imovel_Caracteristica: TZQuery;
    DS_Imovel_Caracteristica: TDataSource;
    Z_Imovel_CaracteristicaID_CARACTERISTICAS: TIntegerField;
    Z_Imovel_CaracteristicaNOME: TStringField;
    Z_Imovel_CaracteristicaOBS: TStringField;
    Z_Imovel_CaracteristicaPADRAO: TStringField;
    Z_Imovel_CaracteristicaATIVO: TStringField;
    Z_Imovel_Subtipo: TZQuery;
    DS_Imovel_Subtipo: TDataSource;
    Z_Imovel: TZQuery;
    DS_Imovel: TDataSource;
    Z_Curinga_03: TZQuery;
    UP_Curinga_03: TZUpdateSQL;
    DS_Curinga_03: TDataSource;
    UP_Imovel: TZUpdateSQL;
    Z_ImovelID_IMOVEL: TIntegerField;
    Z_ImovelID_LOGRADOURO: TIntegerField;
    Z_ImovelID_IMOVEL_SUBTIPO: TIntegerField;
    Z_ImovelID_IMOVEL_TIPO: TIntegerField;
    Z_ImovelID_PESSOA: TIntegerField;
    Z_ImovelNUMERO: TIntegerField;
    Z_ImovelCOMPLEMENTO: TStringField;
    Z_ImovelSTATUS: TStringField;
    Z_ImovelDEPOSITO: TStringField;
    Z_ImovelSEGURO_FIANCA: TStringField;
    Z_ImovelVISITACORRETOR: TStringField;
    Z_ImovelOCUPADO: TStringField;
    Z_ImovelPLACA: TStringField;
    Z_ImovelVENDA: TStringField;
    Z_ImovelALUGUEL: TStringField;
    Z_ImovelOUTROS: TStringField;
    Z_ImovelOUTROS_NOME: TStringField;
    Z_ImovelVALOR_REAL: TFloatField;
    Z_ImovelVALOR_ALUQUEL: TFloatField;
    Z_ImovelVALOR_CONDOMINIO: TFloatField;
    Z_ImovelVALOR_OUTROS: TFloatField;
    Z_ImovelVALOR_OUTROS_NOME: TStringField;
    Z_ImovelAREA_DEPRECIACAO: TStringField;
    Z_ImovelNUM_LUZ: TStringField;
    Z_ImovelNUM_MATRICULA: TStringField;
    Z_ImovelNUM_AGUA: TStringField;
    Z_ImovelENTRADA_CHAVES: TSmallintField;
    Z_ImovelHORARIO_VISITA: TStringField;
    Z_ImovelCHAVE_QUADRO: TStringField;
    Z_ImovelOBS: TStringField;
    Z_ImovelDATA: TDateField;
    Z_ImovelATIVO: TStringField;
    Z_ImovelALTERACAO_FUNC: TIntegerField;
    Z_ImovelALTERACAO_DATA: TDateField;
    Z_ImovelANOTACOES: TMemoField;
    Z_ImovelANUNCIAR: TStringField;
    Z_ImovelEXCLUSIVO: TStringField;
    Z_ImovelLOCAL_PGTO: TStringField;
    Z_ImovelFINALIDADE: TStringField;
    Z_ImovelXSUBTIPO: TStringField;
    Z_ImovelXTIPO: TStringField;
    Z_ImovelXTIPORUA: TStringField;
    Z_ImovelXNOMERUA: TStringField;
    Z_ImovelXCEP: TStringField;
    Z_ImovelXBAIRRO: TStringField;
    Z_ImovelXCIDADE: TStringField;
    Z_ImovelXESTADO: TStringField;
    Z_Curinga_04: TZQuery;
    UP_Curinga_04: TZUpdateSQL;
    DS_Curinga_04: TDataSource;
    Z_Curinga_04ID_PESSOA_IMOVEL: TIntegerField;
    Z_Curinga_04ID_IMOVEL: TIntegerField;
    Z_Curinga_04ID_PESSOA: TIntegerField;
    Z_Curinga_04ID_PESSOA_TIPO: TIntegerField;
    Z_Curinga_04ID_USUARIO: TIntegerField;
    Z_Curinga_04STATUS: TStringField;
    Z_Curinga_04PORCENTAGEM: TFloatField;
    Z_Curinga_04INTERESSE: TStringField;
    Z_Curinga_04VALOR: TFloatField;
    Z_Curinga_04GARANTIA: TStringField;
    Z_Curinga_04FINALIDADE: TStringField;
    Z_Curinga_04DATA_INICIAL: TDateField;
    Z_Curinga_04DATA_FINAL: TDateField;
    Z_Curinga_04HORA_INICIAL: TTimeField;
    Z_Curinga_04HORA_FINAL: TTimeField;
    Z_Curinga_04FORMA_CONTATO: TStringField;
    Z_Curinga_04OBS: TStringField;
    Z_Curinga_04DATA: TDateField;
    Z_Curinga_04ATIVO: TStringField;
    Z_Curinga_04CC: TStringField;
    Z_Curinga_04BANCO: TStringField;
    Z_Curinga_04RESPONSAVEL: TStringField;
    Z_Curinga_04XPESSOA: TStringField;
    Z_Curinga_04XCPF: TStringField;
    Z_Curinga_04XFOTO: TStringField;
    Z_Curinga_05: TZQuery;
    UP_Curinga_05: TZUpdateSQL;
    DS_Curinga_05: TDataSource;
    Z_Curinga_05ID_PESSOA_IMOVEL: TIntegerField;
    Z_Curinga_05ID_IMOVEL: TIntegerField;
    Z_Curinga_05ID_PESSOA: TIntegerField;
    Z_Curinga_05ID_PESSOA_TIPO: TIntegerField;
    Z_Curinga_05ID_USUARIO: TIntegerField;
    Z_Curinga_05STATUS: TStringField;
    Z_Curinga_05PORCENTAGEM: TFloatField;
    Z_Curinga_05INTERESSE: TStringField;
    Z_Curinga_05VALOR: TFloatField;
    Z_Curinga_05GARANTIA: TStringField;
    Z_Curinga_05FINALIDADE: TStringField;
    Z_Curinga_05DATA_INICIAL: TDateField;
    Z_Curinga_05DATA_FINAL: TDateField;
    Z_Curinga_05HORA_INICIAL: TTimeField;
    Z_Curinga_05HORA_FINAL: TTimeField;
    Z_Curinga_05FORMA_CONTATO: TStringField;
    Z_Curinga_05OBS: TStringField;
    Z_Curinga_05DATA: TDateField;
    Z_Curinga_05ATIVO: TStringField;
    Z_Curinga_05CC: TStringField;
    Z_Curinga_05BANCO: TStringField;
    Z_Curinga_05RESPONSAVEL: TStringField;
    Z_Curinga_05XPESSOA: TStringField;
    Z_Curinga_05XCPF: TStringField;
    Z_Curinga_05XFOTO: TStringField;
    Z_Curinga_05LOCAL_PGTO: TStringField;
    Z_Anuncio: TZQuery;
    DS_Anuncio: TDataSource;
    Z_AnuncioID_ANUNCIO: TIntegerField;
    Z_AnuncioID_IMOVEL: TIntegerField;
    Z_AnuncioMEIO: TStringField;
    Z_AnuncioDATA_INICIO: TDateField;
    Z_AnuncioDATA_FIM: TDateField;
    Z_AnuncioVALOR: TFloatField;
    Z_AnuncioDESCRICAO: TMemoField;
    Z_AnuncioOBS: TStringField;
    Z_AnuncioATIVO: TStringField;
    Z_Curinga_06: TZQuery;
    DS_Curinga_06: TDataSource;
    Z_Curinga_04LOCAL_PGTO: TStringField;
    Z_Curinga_04ID_PESSOA2: TIntegerField;
    Z_Curinga_04PESSOA2_NOME: TStringField;
    Z_IPTU: TZQuery;
    DS_IPTU: TDataSource;
    Z_IPTU_Parcela: TZQuery;
    DS_IPTU_Parcela: TDataSource;
    Z_IPTUID_IMOVEL_IPTU: TIntegerField;
    Z_IPTUID_IMOVEL: TIntegerField;
    Z_IPTUCONTRIBUINTE: TStringField;
    Z_IPTURESPONSAVEL: TStringField;
    Z_IPTUVALORVENAL_TERRENO: TFloatField;
    Z_IPTUALIQUOTA_CONSTRUCAO: TFloatField;
    Z_IPTUVALORVENAL_CONSTR_ITBI: TFloatField;
    Z_IPTUVALOR_TOTAL_IPTU: TFloatField;
    Z_IPTUPARCELA_VALOR: TFloatField;
    Z_IPTUNUM_CONTROLE: TStringField;
    Z_IPTUINFORMACOES: TStringField;
    Z_IPTUANO: TStringField;
    Z_IPTUPARCELA_UNICA: TStringField;
    Z_IPTUVALORVENAL_CONSTR_IPTU: TFloatField;
    Z_Reserva: TZQuery;
    Z_ReservaID_PESSOA_IMOVEL: TIntegerField;
    Z_ReservaID_IMOVEL: TIntegerField;
    Z_ReservaID_PESSOA: TIntegerField;
    Z_ReservaID_PESSOA_TIPO: TIntegerField;
    Z_ReservaID_USUARIO: TIntegerField;
    Z_ReservaSTATUS: TStringField;
    Z_ReservaPORCENTAGEM: TFloatField;
    Z_ReservaINTERESSE: TStringField;
    Z_ReservaVALOR: TFloatField;
    Z_ReservaGARANTIA: TStringField;
    Z_ReservaFINALIDADE: TStringField;
    Z_ReservaDATA_INICIAL: TDateField;
    Z_ReservaDATA_FINAL: TDateField;
    Z_ReservaHORA_INICIAL: TTimeField;
    Z_ReservaHORA_FINAL: TTimeField;
    Z_ReservaFORMA_CONTATO: TStringField;
    Z_ReservaOBS: TStringField;
    Z_ReservaDATA: TDateField;
    Z_ReservaATIVO: TStringField;
    Z_ReservaCC: TStringField;
    Z_ReservaBANCO: TStringField;
    Z_ReservaRESPONSAVEL: TStringField;
    Z_ReservaLOCAL_PGTO: TStringField;
    Z_ReservaID_PESSOA2: TIntegerField;
    Z_ReservaPESSOA2_NOME: TStringField;
    Z_ReservaXTIPO: TStringField;
    Z_ReservaXLOGRADOURO: TStringField;
    Z_ReservaXNUMERO: TIntegerField;
    UP_Reserva: TZUpdateSQL;
    DS_Reserva: TDataSource;
    Z_ImovelNOTA: TSmallintField;
    Z_UsuarioID_USUARIO: TIntegerField;
    Z_UsuarioNOME: TStringField;
    Z_UsuarioSENHA: TStringField;
    Z_UsuarioFUNDO: TStringField;
    Z_UsuarioATIVO: TStringField;
    Z_UsuarioADMINISTRADOR: TStringField;
    Z_ImovelPLACA_DATA: TDateField;
    Z_ImovelIMPRIMIR: TStringField;
    Z_Endereco_TipoID_ENDERECO_TIPO: TIntegerField;
    Z_Endereco_TipoTIPO: TStringField;
    Z_Endereco_TipoTELEFONE: TStringField;
    Z_Endereco_TipoENDERECO: TStringField;
    Z_LogradouroID_LOGRADOURO: TIntegerField;
    Z_LogradouroID_CIDADE: TIntegerField;
    Z_LogradouroID_SIGLA: TIntegerField;
    Z_LogradouroID_BAIRRO: TIntegerField;
    Z_LogradouroCEP: TStringField;
    Z_LogradouroTIPO: TStringField;
    Z_LogradouroNOME: TStringField;
    Z_LogradouroXBAIRRO: TStringField;
    Z_LogradouroXCIDADE: TStringField;
    Z_LogradouroXESTADO: TStringField;
    Z_LogradouroXSIGLA: TStringField;
    Z_ImovelDORMITORIOS: TSmallintField;
    Z_Pessoa_TipoID_PESSOA_TIPO: TIntegerField;
    Z_Pessoa_TipoNOME: TStringField;
    Z_Pessoa_TipoOBS: TMemoField;
    Z_Pessoa_TipoPADRAO: TStringField;
    Z_Pessoa_TipoATIVO: TStringField;
    Z_ImovelINTERNET: TStringField;
    Z_Imovel_SubtipoID_IMOVEL_SUBTIPO: TIntegerField;
    Z_Imovel_SubtipoID_IMOVEL_TIPO: TIntegerField;
    Z_Imovel_SubtipoNOME: TStringField;
    Z_Imovel_SubtipoOBS: TStringField;
    Z_Imovel_SubtipoPADRAO: TStringField;
    Z_Imovel_TipoID_IMOVEL_TIPO: TIntegerField;
    Z_Imovel_TipoNOME: TStringField;
    Z_Imovel_TipoOBS: TStringField;
    Z_Imovel_TipoPADRAO: TStringField;
    Z_Imovel_TipoATIVO: TStringField;
    Z_Imovel_TipoCOMERCIAL: TStringField;
    ZqAux: TZQuery;
    Z_ImovelCHAVE: TStringField;
    Z_IPTUPARCELA_QTDE: TIntegerField;
    ZqAux2: TZQuery;
    Z_ImovelAREA_L: TFloatField;
    Z_ImovelAREA_C: TFloatField;
    Z_ImovelAREA_FATOR: TFloatField;
    Z_ImovelAREA_CONSTRUIDA: TFloatField;
    Z_ImovelAREA_CONSTRUIDA_FATOR: TFloatField;
    Z_ImovelAREA_OUTROS: TFloatField;
    Z_ImovelAREA_OUTROS_FATOR: TFloatField;
    Z_Status: TZQuery;
    Z_StatusID_STATUS: TIntegerField;
    Z_StatusNOME: TStringField;
    Z_StatusOBS: TBlobField;
    Z_StatusPADRAO: TStringField;
    Z_StatusATIVO: TStringField;
    Z_UsuarioEMAIL: TStringField;
    Z_PessoaID_PESSOA: TIntegerField;
    Z_PessoaID_PESSOA_TIPO: TIntegerField;
    Z_PessoaID_USUARIO: TIntegerField;
    Z_PessoaID_OCUPACAO: TIntegerField;
    Z_PessoaPESSOA_FISICA: TStringField;
    Z_PessoaNOME: TStringField;
    Z_PessoaNOME_FANTASIA: TStringField;
    Z_PessoaCPF_CNPJ: TStringField;
    Z_PessoaRG_IE: TStringField;
    Z_PessoaRG_EMISSAO: TDateField;
    Z_PessoaRG_ORGAO: TStringField;
    Z_PessoaIM: TStringField;
    Z_PessoaSEXO: TStringField;
    Z_PessoaPAI: TStringField;
    Z_PessoaMAE: TStringField;
    Z_PessoaCONJUGE: TStringField;
    Z_PessoaNACIONALIDADE: TStringField;
    Z_PessoaESTADO_CIVIL: TStringField;
    Z_PessoaEMPRESA: TStringField;
    Z_PessoaEMPRESA_CARGO: TStringField;
    Z_PessoaEMPRESA_RENDA: TFloatField;
    Z_PessoaEMPRESA_TEMPO: TDateField;
    Z_PessoaCONSULTA_SPC: TStringField;
    Z_PessoaCONSULTA_CERASA: TStringField;
    Z_PessoaCONSULTA_TELEFONE: TStringField;
    Z_PessoaCONSULTA_OUTROS: TStringField;
    Z_PessoaCONSULTA_DADOS: TMemoField;
    Z_PessoaCREDITO: TFloatField;
    Z_PessoaCREDITO_VAL: TDateField;
    Z_PessoaCREDITO_VAL_ATIVO: TStringField;
    Z_PessoaNOTA: TSmallintField;
    Z_PessoaNASCIMENTO: TDateField;
    Z_PessoaCOMISSAO: TFloatField;
    Z_PessoaDESCONTO: TFloatField;
    Z_PessoaFILHOS: TStringField;
    Z_PessoaFOTO: TStringField;
    Z_PessoaEMAIL: TStringField;
    Z_PessoaMSN: TStringField;
    Z_PessoaICQ: TStringField;
    Z_PessoaYAHOO: TStringField;
    Z_PessoaAIM: TStringField;
    Z_PessoaMALADIRETA: TStringField;
    Z_PessoaDATA: TDateTimeField;
    Z_PessoaOBS: TStringField;
    Z_PessoaATIVO: TStringField;
    Z_PessoaALTERACAO_FUNC: TSmallintField;
    Z_PessoaALTERACAO_DATA: TDateField;
    Z_PessoaIMPRIMIR: TStringField;
    Z_PessoaPESSOA_RESPONSAVEL: TIntegerField;
    Z_PessoaSENHA: TStringField;
    Z_PessoaOCUPACAO: TStringField;
    Z_PessoaTIPO: TStringField;
    Z_PessoaXTELEFONE: TStringField;
    Z_Agenda: TZQuery;
    UP_Agenda: TZUpdateSQL;
    Z_AgendaID_AGENDA: TIntegerField;
    Z_AgendaID_REMETENTE: TIntegerField;
    Z_AgendaID_DESTINATARIO: TIntegerField;
    Z_AgendaIMPORTANCIA: TIntegerField;
    Z_AgendaDATA_CAD: TDateTimeField;
    Z_AgendaDATA_REF: TDateTimeField;
    Z_AgendaMENSAGEM: TMemoField;
    Z_AgendaATIVO: TStringField;
    Z_AgendaMSG: TStringField;
    Z_AgendaNOME: TStringField;
    Z_AgendaEMAIL: TStringField;
    Z_ImovelPROPRIETARIO: TStringField;
    Z_ImovelVALOR_VENDA: TFloatField;
    Z_Curinga_01X: TZQuery;
    DS_Curinga_01X: TDataSource;
    Z_Curinga_02X: TZQuery;
    DS_Curinga_02X: TDataSource;
    Z_Curinga_03X: TZQuery;
    UP_Curinga_03X: TZUpdateSQL;
    DS_Curinga_03X: TDataSource;
    procedure Z_PessoaBeforePost(DataSet: TDataSet);
    procedure Z_ImovelBeforePost(DataSet: TDataSet);
    procedure Z_IPTU_ParcelaNewRecord(DataSet: TDataSet);
    procedure Z_IPTUNewRecord(DataSet: TDataSet);
    procedure Z_Imovel_SubtipoNewRecord(DataSet: TDataSet);
    procedure Z_PessoaNASCIMENTOSetText(Sender: TField; const Text: string);
    procedure Z_ImovelPLACA_DATASetText(Sender: TField; const Text: string);
    procedure Z_PessoaCREDITO_VALSetText(Sender: TField; const Text: string);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  DM_CADASTRO: TDM_CADASTRO;

implementation

uses FrmPrincipal, unCamposBusca, unMsg, FrmImovel, unINI;

{$R *.dfm}

procedure TDM_CADASTRO.Z_ImovelBeforePost(DataSet: TDataSet);
begin
     Z_Imovel.FieldByName('ALTERACAO_FUNC').AsString := getUser('CODIGO_USUARIO');
     Z_Imovel.FieldByName('ALTERACAO_DATA').AsDateTime := Date();
end;

procedure TDM_CADASTRO.Z_ImovelPLACA_DATASetText(Sender: TField;
  const Text: string);
begin
  SENDER.AsString := principal.TratarData(text);
end;

procedure TDM_CADASTRO.Z_Imovel_SubtipoNewRecord(DataSet: TDataSet);
begin
{     unCamposBusca.BUSCA(DM_Cadastro.Z_Curinga_02, 'select ID from SP_GEN_IMOVEL_SUBTIPO_ID');
     DM_Cadastro.Z_Imovel_Subtipo.FieldByName('ID_IMOVEL_SUBTIPO').Value := DM_Cadastro.Z_Curinga_02.FieldByName('ID').Value;
     DM_Cadastro.Z_Curinga_02.Close;
     DM_Cadastro.Z_Imovel_Subtipo.FieldByName('PADRAO').Value := 'NAO';
}
end;

procedure TDM_CADASTRO.Z_IPTUNewRecord(DataSet: TDataSet);
begin

     unCamposBusca.BUSCA(DM_Cadastro.Z_Curinga_01, 'select ID from SP_GEN_IMOVEL_IPTU_ID');

     DM_Cadastro.Z_IPTU.FieldByName('ID_IMOVEL_IPTU').Value := DM_Cadastro.Z_Curinga_01.FieldByName('ID').Value;

     DM_Cadastro.Z_Curinga_01.Close;

     DM_Cadastro.Z_IPTU.FieldByName('PARCELA_UNICA').Value := 'NAO';
     DM_Cadastro.Z_IPTU.FieldByName('PARCELA_QTDE').Value := 0;
     DM_Cadastro.Z_IPTU.FieldByName('PARCELA_VALOR').Value := 0;
     DM_Cadastro.Z_IPTU.FieldByName('VALOR_TOTAL_IPTU').Value := 0;
     DM_Cadastro.Z_IPTU.FieldByName('VALORVENAL_CONSTR_IPTU').Value := 0;
     DM_Cadastro.Z_IPTU.FieldByName('VALORVENAL_CONSTR_ITBI').Value := 0;
     DM_Cadastro.Z_IPTU.FieldByName('ALIQUOTA_CONSTRUCAO').Value := 0;
     DM_Cadastro.Z_IPTU.FieldByName('VALORVENAL_TERRENO').Value := 0;

 
end;

procedure TDM_CADASTRO.Z_IPTU_ParcelaNewRecord(DataSet: TDataSet);
begin
     unCamposBusca.BUSCA(DM_Cadastro.Z_Curinga_01, 'select ID from SP_GEN_IPTU_PARCELAS_ID');

     DM_Cadastro.Z_IPTU_Parcela.FieldByName('ID_IPTU_PARCELAS').Value := DM_Cadastro.Z_Curinga_01.FieldByName('ID').Value;

     DM_Cadastro.Z_Curinga_01.Close;

     DM_Cadastro.Z_IPTU_Parcela.FieldByName('PARCELA').Value := '0';
     DM_Cadastro.Z_IPTU_Parcela.FieldByName('VALOR').Value := 0;
     DM_Cadastro.Z_IPTU_Parcela.FieldByName('QUITADO').Value := 'NAO';

end;

procedure TDM_CADASTRO.Z_PessoaBeforePost(DataSet: TDataSet);
begin
     Z_Pessoa.FieldByName('ALTERACAO_FUNC').AsString := getUser('CODIGO_USUARIO');
     Z_Pessoa.FieldByName('ALTERACAO_DATA').AsDateTime := Date();
end;

procedure TDM_CADASTRO.Z_PessoaCREDITO_VALSetText(Sender: TField;
  const Text: string);
begin
  SENDER.AsString := principal.TratarData(text);
end;

procedure TDM_CADASTRO.Z_PessoaNASCIMENTOSetText(Sender: TField;
  const Text: string);
begin
  SENDER.AsString := principal.TratarData(text);
end;

end.
