unit FrmDM_FINANCEIRO;

interface

uses
  SysUtils, Classes, DB, ZAbstractRODataset, ZAbstractDataset, ZDataset,
  ZSqlUpdate;

type
  TDM_FINANCEIRO = class(TDataModule)
    ZContaEntrada: TZQuery;
    UpContaEntrada: TZUpdateSQL;
    ZContaEntradaRecibo: TZQuery;
    ZContaSaidaRecibo: TZQuery;
    ZContaSubgrupo: TZQuery;
    ZContaGrupo: TZQuery;
    ZContaSubgrupoID_CONTA_SUBGRUPO: TIntegerField;
    ZContaSubgrupoNOME: TStringField;
    ZContaSubgrupoOBS: TStringField;
    ZContaSubgrupoPADRAO: TStringField;
    ZContaSubgrupoATIVO: TStringField;
    ZContaGrupoID_CONTA_GRUPO: TIntegerField;
    ZContaGrupoNOME: TStringField;
    ZContaGrupoOBS: TStringField;
    ZContaGrupoPADRAO: TStringField;
    ZContaGrupoATIVO: TStringField;
    ZConta: TZQuery;
    ZContaID_CONTAS: TIntegerField;
    ZContaDATA_ABERTURA: TDateField;
    ZContaAGENCIA: TStringField;
    ZContaCONTA: TStringField;
    ZContaSALDO_INICIAL: TFloatField;
    ZContaBANCO: TStringField;
    ZContaOBS: TStringField;
    ZContaDATA: TDateField;
    ZContaPADRAO: TStringField;
    ZContaATIVO: TStringField;
    ZForma: TZQuery;
    ZFormaID_CONTA_FORMA: TIntegerField;
    ZFormaNOME: TStringField;
    ZFormaOBS: TStringField;
    ZFormaATIVO: TStringField;
    ZCheque: TZQuery;
    ZContaSaida: TZQuery;
    ZContaSaidaID_CONTAS_ENTADA: TIntegerField;
    ZContaSaidaID_CONTA_TIPO: TIntegerField;
    ZContaSaidaID_CONTA_SUBTIPO: TIntegerField;
    ZContaSaidaID_PESSOA: TIntegerField;
    ZContaSaidaID_IMOVEL: TIntegerField;
    ZContaSaidaID_CONTAS: TIntegerField;
    ZContaSaidaID_FUNCIONARIO: TIntegerField;
    ZContaSaidaID_CONTRATO: TIntegerField;
    ZContaSaidaID_CONTA_FORMA: TIntegerField;
    ZContaSaidaDATA_REF: TDateField;
    ZContaSaidaDOCUMENTO: TStringField;
    ZContaSaidaOPERACAO: TStringField;
    ZContaSaidaVALOR: TFloatField;
    ZContaSaidaPARCELADO: TStringField;
    ZContaSaidaPARCELA: TSmallintField;
    ZContaSaidaPARCELA_TOTAL: TSmallintField;
    ZContaSaidaOBS: TStringField;
    ZContaSaidaATIVO: TStringField;
    ZContaSaidaATIVO_EXTRA: TStringField;
    ZContaSaidaDESCONTO: TFloatField;
    ZContaSaidaID_FUNCIONARIO_BAIXA: TIntegerField;
    ZContaSaidaXCONTA: TStringField;
    ZContaSaidaXGRUPO: TStringField;
    ZContaSaidaXSUBGRUPO: TStringField;
    ZContaSaidaJUROS: TFloatField;
    ZContaSaidaMULTA: TFloatField;
    ZContaSaidaVALORTOTAL: TFloatField;
    ZContaSaidaDATA_PGTO: TDateTimeField;
    ZContaSaidaDATA: TDateTimeField;
    ZqItensContaEntrada: TZQuery;
    dsItensContaEntrada: TDataSource;
    ZContaTipo: TZQuery;
    ZContaSubtipo: TZQuery;
    ZqItensContaSaida: TZQuery;
    ZqItensContaSaidaID_CONTAS_ENTADA: TIntegerField;
    ZqItensContaSaidaID_CONTA_TIPO: TIntegerField;
    ZqItensContaSaidaID_CONTA_SUBTIPO: TIntegerField;
    ZqItensContaSaidaID_PESSOA: TIntegerField;
    ZqItensContaSaidaID_IMOVEL: TIntegerField;
    ZqItensContaSaidaID_CONTAS: TIntegerField;
    ZqItensContaSaidaID_FUNCIONARIO: TIntegerField;
    ZqItensContaSaidaID_CONTRATO: TIntegerField;
    ZqItensContaSaidaID_CONTA_FORMA: TIntegerField;
    ZqItensContaSaidaDATA_PGTO: TDateTimeField;
    ZqItensContaSaidaDATA_REF: TDateField;
    ZqItensContaSaidaDOCUMENTO: TStringField;
    ZqItensContaSaidaOPERACAO: TStringField;
    ZqItensContaSaidaVALOR: TFloatField;
    ZqItensContaSaidaPARCELADO: TStringField;
    ZqItensContaSaidaPARCELA: TSmallintField;
    ZqItensContaSaidaPARCELA_TOTAL: TSmallintField;
    ZqItensContaSaidaOBS: TStringField;
    ZqItensContaSaidaDATA: TDateTimeField;
    ZqItensContaSaidaATIVO: TStringField;
    ZqItensContaSaidaATIVO_EXTRA: TStringField;
    ZqItensContaSaidaDESCONTO: TFloatField;
    ZqItensContaSaidaID_FUNCIONARIO_BAIXA: TIntegerField;
    ZqItensContaSaidaJUROS: TFloatField;
    ZqItensContaSaidaMULTA: TFloatField;
    dsItensContaSaida: TDataSource;
    ZqItensContaSaidaGRUPO: TStringField;
    ZqItensContaSaidaSUBGRUPO: TStringField;
    ZqItensContaEntradaID_CONTAS_ENTADA: TIntegerField;
    ZqItensContaEntradaID_CONTA_TIPO: TIntegerField;
    ZqItensContaEntradaID_CONTA_SUBTIPO: TIntegerField;
    ZqItensContaEntradaID_PESSOA: TIntegerField;
    ZqItensContaEntradaID_IMOVEL: TIntegerField;
    ZqItensContaEntradaID_CONTAS: TIntegerField;
    ZqItensContaEntradaID_FUNCIONARIO: TIntegerField;
    ZqItensContaEntradaID_CONTRATO: TIntegerField;
    ZqItensContaEntradaID_CONTA_FORMA: TIntegerField;
    ZqItensContaEntradaDATA_PGTO: TDateTimeField;
    ZqItensContaEntradaDATA_REF: TDateField;
    ZqItensContaEntradaDOCUMENTO: TStringField;
    ZqItensContaEntradaOPERACAO: TStringField;
    ZqItensContaEntradaVALOR: TFloatField;
    ZqItensContaEntradaPARCELADO: TStringField;
    ZqItensContaEntradaPARCELA: TSmallintField;
    ZqItensContaEntradaPARCELA_TOTAL: TSmallintField;
    ZqItensContaEntradaOBS: TStringField;
    ZqItensContaEntradaDATA: TDateTimeField;
    ZqItensContaEntradaATIVO: TStringField;
    ZqItensContaEntradaATIVO_EXTRA: TStringField;
    ZqItensContaEntradaDESCONTO: TFloatField;
    ZqItensContaEntradaID_FUNCIONARIO_BAIXA: TIntegerField;
    ZqItensContaEntradaJUROS: TFloatField;
    ZqItensContaEntradaMULTA: TFloatField;
    ZqItensContaEntradaVALORTOTAL: TFloatField;
    ZqItensContaEntradaGRUPO: TStringField;
    ZqItensContaEntradaSUBGRUPO: TStringField;
    ZContaEntradaID_CONTAS_ENTADA: TIntegerField;
    ZContaEntradaID_CONTA_TIPO: TIntegerField;
    ZContaEntradaID_CONTA_SUBTIPO: TIntegerField;
    ZContaEntradaID_PESSOA: TIntegerField;
    ZContaEntradaID_IMOVEL: TIntegerField;
    ZContaEntradaID_CONTAS: TIntegerField;
    ZContaEntradaID_FUNCIONARIO: TIntegerField;
    ZContaEntradaID_CONTRATO: TIntegerField;
    ZContaEntradaID_CONTA_FORMA: TIntegerField;
    ZContaEntradaDATA_PGTO: TDateTimeField;
    ZContaEntradaDATA_REF: TDateField;
    ZContaEntradaDOCUMENTO: TStringField;
    ZContaEntradaOPERACAO: TStringField;
    ZContaEntradaVALOR: TFloatField;
    ZContaEntradaPARCELADO: TStringField;
    ZContaEntradaPARCELA: TSmallintField;
    ZContaEntradaPARCELA_TOTAL: TSmallintField;
    ZContaEntradaOBS: TStringField;
    ZContaEntradaDATA: TDateTimeField;
    ZContaEntradaATIVO: TStringField;
    ZContaEntradaATIVO_EXTRA: TStringField;
    ZContaEntradaDESCONTO: TFloatField;
    ZContaEntradaID_FUNCIONARIO_BAIXA: TIntegerField;
    ZContaEntradaJUROS: TFloatField;
    ZContaEntradaMULTA: TFloatField;
    ZContaEntradaVALORTOTAL: TFloatField;
    ZContaEntradaID_CONTA_ENTRADA: TIntegerField;
    ZContaEntradaXCONTA: TStringField;
    ZContaEntradaXGRUPO: TStringField;
    ZContaEntradaXSUBGRUPO: TStringField;
    ZqContaCheque: TZQuery;
    ZqAux: TZQuery;
    ZContaEntradaNOME: TStringField;
    ZContaSaidaNOME: TStringField;
    UpContaSaida: TZUpdateSQL;
    ZCaixa: TZQuery;
    ZCaixaCategoria: TZQuery;
    ZCaixaGrupo: TZQuery;
    ZCaixaSubgrupo: TZQuery;
    DS_CaixaCategoria: TDataSource;
    DS_CaixaGrupo: TDataSource;
    DS_CaixaSubgrupo: TDataSource;
    ZCaixaPgto: TZQuery;
    DS_CaixaPgto: TDataSource;
    ZCaixaFormaPgto: TZQuery;
    DS_CaixaFormaPgto: TDataSource;
    ZUpdateCaixa: TZUpdateSQL;
    ZCaixaPgtoID_CAIXA_PGTO: TIntegerField;
    ZCaixaPgtoID_CAIXA_ENTRADA: TIntegerField;
    ZCaixaPgtoID_CAIXA_SAIDA: TIntegerField;
    ZCaixaPgtoID_FORMA_PGTO: TIntegerField;
    ZCaixaPgtoID_FUNCIONARIO: TIntegerField;
    ZCaixaPgtoDATA_CAD: TDateTimeField;
    ZCaixaPgtoDATA_RECEBIMENTO: TDateTimeField;
    ZCaixaPgtoDATA_PGTO: TDateField;
    ZCaixaPgtoANOTACAO: TStringField;
    ZCaixaPgtoVALOR: TFloatField;
    ZCaixaPgtoNOME: TStringField;
    ZUpdateCaixaPgto: TZUpdateSQL;
    ZCaixaTipoStatus: TZQuery;
    DS_CaixaTipoStatus: TDataSource;
    ZCaixaStatus: TZQuery;
    DS_CaixaStatus: TDataSource;
    ZCaixaStatusID_CAIXA_STATUS: TIntegerField;
    ZCaixaStatusID_STATUS: TIntegerField;
    ZCaixaStatusID_CAIXA_SAIDA: TIntegerField;
    ZCaixaStatusID_CAIXA_ENTRADA: TIntegerField;
    ZCaixaStatusID_FUNCIONARIO: TIntegerField;
    ZCaixaStatusDATA_CAD: TDateTimeField;
    ZCaixaStatusDATA_ENTRADA: TDateField;
    ZCaixaStatusDATA_SAIDA: TDateField;
    ZCaixaStatusDATA_ALT: TDateTimeField;
    ZCaixaStatusANOTACAO: TMemoField;
    ZCaixaStatusNOME: TStringField;
    ZUpdatecaixaStatus: TZUpdateSQL;
    ZLog: TZQuery;
    DS_Log: TDataSource;
    ZLogID_LOG: TIntegerField;
    ZLogACAO: TStringField;
    ZLogCOMPONENTE: TStringField;
    ZLogCAMPOS: TMemoField;
    ZLogDATA: TDateTimeField;
    ZLogID_FUNC: TIntegerField;
    ZLogID_CONTA: TIntegerField;
    ZLogOBS: TStringField;
    ZLogATIVO: TStringField;
    ZCaixaBackup: TZQuery;
    DS_CaixaBackup: TDataSource;
    DS_CaixaSimples: TDataSource;
    ZCaixaSimples: TZQuery;
    ZCaixaSimplesCATEGORIA: TStringField;
    ZCaixaSimplesTIPO: TStringField;
    ZCaixaSimplesSUBTIPO: TStringField;
    ZCaixaSimplesPESSOA: TStringField;
    ZCaixaSimplesLOGRADOURO: TStringField;
    ZCaixaSimplesNUMERO: TIntegerField;
    ZCaixaSimplesCOMPLEMENTO: TStringField;
    ZCaixaSimplesID_CAIXA: TIntegerField;
    ZCaixaSimplesID_CATEGORIA: TIntegerField;
    ZCaixaSimplesID_SUBTIPO: TIntegerField;
    ZCaixaSimplesID_TIPO: TIntegerField;
    ZCaixaSimplesID_PESSOA: TIntegerField;
    ZCaixaSimplesID_IMOVEL: TIntegerField;
    ZCaixaSimplesID_CONTRATO: TIntegerField;
    ZCaixaSimplesID_FUNCIONARIO: TIntegerField;
    ZCaixaSimplesID_ENTRADA: TIntegerField;
    ZCaixaSimplesID_SAIDA: TIntegerField;
    ZCaixaSimplesDATA_REF: TDateField;
    ZCaixaSimplesDATA_CAD: TDateTimeField;
    ZCaixaSimplesDATA_ALT: TDateTimeField;
    ZCaixaSimplesDATA_PGTO: TDateField;
    ZCaixaSimplesHORA_PGTO: TTimeField;
    ZCaixaSimplesDOCUMENTO: TStringField;
    ZCaixaSimplesOPERACAO: TStringField;
    ZCaixaSimplesPARCELA: TIntegerField;
    ZCaixaSimplesPENDENTE: TStringField;
    ZCaixaSimplesANOTACAO: TMemoField;
    ZCaixaSimplesATIVO: TStringField;
    ZCaixaSimplesVALORREAL: TFloatField;
    ZUpdateCaixaSimples: TZUpdateSQL;
    ZCaixaSimplesGARANTIDO: TStringField;
    ZChequeConta: TZQuery;
    DSChequeConta: TDataSource;
    ZChequeContaUpdate: TZUpdateSQL;
    ZChequeID_CHEQUE: TIntegerField;
    ZChequeBANCO: TStringField;
    ZChequeAGENCIA: TStringField;
    ZChequeCC: TStringField;
    ZChequeNUM_CHEQUE: TStringField;
    ZChequeDATA_ENTRADA: TDateField;
    ZChequeID_FUNCIONARIO: TIntegerField;
    ZChequeID_PESSOA: TIntegerField;
    ZChequeNOME: TStringField;
    ZChequeRG: TStringField;
    ZChequeCPF: TStringField;
    ZChequeENDERECO: TStringField;
    ZChequeTELEFONE1: TStringField;
    ZChequeTELEFONE2: TStringField;
    ZChequeVALOR: TFloatField;
    ZChequeOBS: TStringField;
    ZChequeDATA_REF: TDateField;
    ZChequeATIVO: TStringField;
    ZChequeDATA_BAIXA: TDateField;
    ZChequeNOME_NORMAL: TStringField;
    ZChequeNOME_FANTASIA: TStringField;
    ZUpdateCheque: TZUpdateSQL;
    ZChequeContaID_CONTA_CHEQUE: TIntegerField;
    ZChequeContaID_CHEQUE: TIntegerField;
    ZChequeContaID_CONTA: TIntegerField;
    ZChequeContaOPERACAO: TStringField;
    ZChequeContaID_FUNCIONARIO: TIntegerField;
    ZChequeContaOBS: TStringField;
    ZChequeContaID_CHEQUE_1: TIntegerField;
    ZChequeContaBANCO: TStringField;
    ZChequeContaAGENCIA: TStringField;
    ZChequeContaCC: TStringField;
    ZChequeContaNUM_CHEQUE: TStringField;
    ZChequeContaDATA_ENTRADA: TDateField;
    ZChequeContaID_FUNCIONARIO_1: TIntegerField;
    ZChequeContaID_PESSOA: TIntegerField;
    ZChequeContaNOME: TStringField;
    ZChequeContaRG: TStringField;
    ZChequeContaCPF: TStringField;
    ZChequeContaENDERECO: TStringField;
    ZChequeContaTELEFONE1: TStringField;
    ZChequeContaTELEFONE2: TStringField;
    ZChequeContaVALOR: TFloatField;
    ZChequeContaOBS_1: TStringField;
    ZChequeContaDATA_REF: TDateField;
    ZChequeContaATIVO: TStringField;
    ZChequeContaDATA_BAIXA: TDateField;
    ZCaixaSimplesVALOR: TFloatField;
    ZCaixaSimplesVALOR_JUROS: TFloatField;
    ZCaixaSimplesVALOR_MULTA: TFloatField;
    ZCaixaSimplesVALOR_DESCONTO: TFloatField;
    ZCaixaID_CAIXA: TIntegerField;
    ZCaixaID_CATEGORIA: TIntegerField;
    ZCaixaID_TIPO: TIntegerField;
    ZCaixaID_SUBTIPO: TIntegerField;
    ZCaixaID_PESSOA: TIntegerField;
    ZCaixaID_IMOVEL: TIntegerField;
    ZCaixaID_CONTRATO: TIntegerField;
    ZCaixaID_FUNCIONARIO: TIntegerField;
    ZCaixaID_ENTRADA: TIntegerField;
    ZCaixaID_SAIDA: TIntegerField;
    ZCaixaDATA_REF: TDateField;
    ZCaixaDATA_CAD: TDateTimeField;
    ZCaixaDATA_ALT: TDateTimeField;
    ZCaixaDATA_PGTO: TDateField;
    ZCaixaHORA_PGTO: TTimeField;
    ZCaixaDOCUMENTO: TStringField;
    ZCaixaOPERACAO: TStringField;
    ZCaixaVALOR: TFloatField;
    ZCaixaVALOR_JUROS: TFloatField;
    ZCaixaVALOR_MULTA: TFloatField;
    ZCaixaVALOR_DESCONTO: TFloatField;
    ZCaixaPARCELA: TIntegerField;
    ZCaixaPENDENTE: TStringField;
    ZCaixaANOTACAO: TMemoField;
    ZCaixaATIVO: TStringField;
    ZCaixaGARANTIDO: TStringField;
    ZCaixaPESSOA: TStringField;
    ZCaixaRUA: TStringField;
    ZCaixaCATEGORIA2: TStringField;
    ZCaixaGRUPO2: TStringField;
    ZCaixaSUBGRUPO2: TStringField;
    ZCaixaCONTRATO_REF: TLargeintField;
    ZCaixaCOMPLEMENTO: TStringField;
    ZCaixaVALORREAL: TFloatField;
    ZCaixaPAGO: TStringField;
    ZCaixaPARCELATOTAL: TIntegerField;
    ZCaixaBackupID_CAIXA: TIntegerField;
    ZCaixaBackupID_CATEGORIA: TIntegerField;
    ZCaixaBackupID_TIPO: TIntegerField;
    ZCaixaBackupID_SUBTIPO: TIntegerField;
    ZCaixaBackupID_PESSOA: TIntegerField;
    ZCaixaBackupID_IMOVEL: TIntegerField;
    ZCaixaBackupID_CONTRATO: TIntegerField;
    ZCaixaBackupID_FUNCIONARIO: TIntegerField;
    ZCaixaBackupID_ENTRADA: TIntegerField;
    ZCaixaBackupID_SAIDA: TIntegerField;
    ZCaixaBackupDATA_REF: TDateField;
    ZCaixaBackupDATA_CAD: TDateTimeField;
    ZCaixaBackupDATA_ALT: TDateTimeField;
    ZCaixaBackupDATA_PGTO: TDateField;
    ZCaixaBackupHORA_PGTO: TTimeField;
    ZCaixaBackupDOCUMENTO: TStringField;
    ZCaixaBackupOPERACAO: TStringField;
    ZCaixaBackupVALOR: TFloatField;
    ZCaixaBackupVALOR_JUROS: TFloatField;
    ZCaixaBackupVALOR_MULTA: TFloatField;
    ZCaixaBackupVALOR_DESCONTO: TFloatField;
    ZCaixaBackupPARCELA: TIntegerField;
    ZCaixaBackupPENDENTE: TStringField;
    ZCaixaBackupANOTACAO: TMemoField;
    ZCaixaBackupATIVO: TStringField;
    ZCaixaBackupGARANTIDO: TStringField;
    ZCaixaBackupPESSOA: TStringField;
    ZCaixaBackupRUA: TStringField;
    ZCaixaBackupCATEGORIA: TStringField;
    ZCaixaBackupGRUPO: TStringField;
    ZCaixaBackupSUBGRUPO: TStringField;
    ZCaixaBackupCONTRATO_REF: TLargeintField;
    ZCaixaBackupCOMPLEMENTO: TStringField;
    ZCaixaBackupVALORREAL: TFloatField;
    ZCaixaBackupPAGO: TStringField;
    ZCaixaBackupPARCELATOTAL: TIntegerField;
    ZLogs_Banco: TZQuery;
    DS_Logs_Banco: TDataSource;
    procedure ZChequeDATA_BAIXASetText(Sender: TField; const Text: string);
    procedure ZContaEntradaDATA_REFSetText(Sender: TField; const Text: string);
    procedure ZContaEntradaDATASetText(Sender: TField; const Text: string);
    procedure ZContaSaidaDATA_REFSetText(Sender: TField; const Text: string);
    procedure ZContaSaidaDATASetText(Sender: TField; const Text: string);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  DM_FINANCEIRO: TDM_FINANCEIRO;
  Cod: integer;

implementation

uses FrmPrincipal, unCamposBusca;

{$R *.dfm}

procedure TDM_FINANCEIRO.ZChequeDATA_BAIXASetText(Sender: TField;
  const Text: string);
begin
  SENDER.AsString := principal.TratarData(text);
end;

procedure TDM_FINANCEIRO.ZContaEntradaDATASetText(Sender: TField;
  const Text: string);
begin
  SENDER.AsString := principal.TratarData(text);
end;

procedure TDM_FINANCEIRO.ZContaEntradaDATA_REFSetText(Sender: TField;
  const Text: string);
begin
  SENDER.AsString := principal.TratarData(text);
end;

procedure TDM_FINANCEIRO.ZContaSaidaDATASetText(Sender: TField;
  const Text: string);
begin
  SENDER.AsString := principal.TratarData(text);
end;

procedure TDM_FINANCEIRO.ZContaSaidaDATA_REFSetText(Sender: TField;
  const Text: string);
begin
  SENDER.AsString := principal.TratarData(text);
end;

end.
